name: Create Release

on:
  push:
    tags:
      - 'v*.*.*-cn'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get current tag
      id: get_tag
      run: |
        # Get the current tag that triggered this workflow
        CURRENT_TAG=${{ github.ref_name }}
        echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
        echo "Using tag: $CURRENT_TAG"
        
    - name: Check if release already exists
      id: check_release
      run: |
        if gh release view ${{ steps.get_tag.outputs.current_tag }} >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Release ${{ steps.get_tag.outputs.current_tag }} already exists, skipping..."
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Release ${{ steps.get_tag.outputs.current_tag }} does not exist, proceeding..."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create release package variants
      if: steps.check_release.outputs.exists == 'false'
      run: |
        chmod +x .github/workflows/scripts/create-release-packages.sh
        .github/workflows/scripts/create-release-packages.sh ${{ steps.get_tag.outputs.current_tag }}
        
    - name: Generate release notes
      if: steps.check_release.outputs.exists == 'false'
      id: release_notes
      run: |
        # Get commits since last non-CN tag
        LAST_CN_TAG=$(git describe --tags --match="v*.*.*-cn" --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -z "$LAST_CN_TAG" ]; then
          # Find the last regular tag to compare against
          LAST_REGULAR_TAG=$(git describe --tags --match="v*.*.*" --exclude="*-*-cn" --abbrev=0 HEAD~1 2>/dev/null || echo "")
          if [ -z "$LAST_REGULAR_TAG" ]; then
            # If no previous tags, get last 20 commits
            COMMITS=$(git log --oneline --pretty=format:"- %s" HEAD~20..HEAD)
          else
            COMMITS=$(git log --oneline --pretty=format:"- %s" $LAST_REGULAR_TAG..HEAD)
          fi
        else
          COMMITS=$(git log --oneline --pretty=format:"- %s" $LAST_CN_TAG..HEAD)
        fi

        # Create release notes
        cat > release_notes.md << EOF
        Spec Kit CN 中文模板发布 ${{ steps.get_tag.outputs.current_tag }}

        Updated specification-driven development templates for multiple AI assistants including GitHub Copilot, Claude Code, Gemini CLI, Cursor, Qwen, OpenCode, Windsurf, Codex, Kilocode, Auggie, and Roo.

        Download the template for your preferred AI assistant and script type:
        - spec-kit-cn-template-copilot-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-copilot-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-claude-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-claude-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-gemini-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-gemini-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-cursor-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-cursor-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-qwen-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-qwen-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-opencode-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-opencode-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-windsurf-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-windsurf-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-codex-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-codex-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-kilocode-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-kilocode-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-auggie-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-auggie-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-roo-sh-${{ steps.get_tag.outputs.current_tag }}.zip
        - spec-kit-cn-template-roo-ps-${{ steps.get_tag.outputs.current_tag }}.zip
        EOF
        
        echo "Generated release notes:"
        cat release_notes.md
        
    - name: Create GitHub Release
      if: steps.check_release.outputs.exists == 'false'
      run: |
        # Remove 'v' prefix from version for release title
        VERSION_NO_V=${{ steps.get_tag.outputs.current_tag }}
        VERSION_NO_V=${VERSION_NO_V#v}

        gh release create ${{ steps.get_tag.outputs.current_tag }} \
          spec-kit-cn-template-copilot-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-copilot-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-claude-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-claude-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-gemini-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-gemini-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-cursor-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-cursor-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-qwen-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-qwen-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-opencode-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-opencode-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-windsurf-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-windsurf-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-codex-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-codex-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-kilocode-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-kilocode-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-auggie-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-auggie-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-roo-sh-${{ steps.get_tag.outputs.current_tag }}.zip \
          spec-kit-cn-template-roo-ps-${{ steps.get_tag.outputs.current_tag }}.zip \
          --title "Spec Kit CN 中文模板 - $VERSION_NO_V" \
          --notes-file release_notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update version in pyproject.toml (for release artifacts only)
      if: steps.check_release.outputs.exists == 'false'
      run: |
        # Update version in pyproject.toml (remove 'v' prefix for Python versioning)
        VERSION=${{ steps.get_tag.outputs.current_tag }}
        PYTHON_VERSION=${VERSION#v}
        
        if [ -f "pyproject.toml" ]; then
          sed -i "s/version = \".*\"/version = \"$PYTHON_VERSION\"/" pyproject.toml
          echo "Updated pyproject.toml version to $PYTHON_VERSION (for release artifacts only)"
        fi
        
    # Note: No longer committing version changes back to main branch
    # The version is only updated in the release artifacts
